server:
  port: 8082
  context-path: /mtg-my-card-collection

spring:
  data:
    mongodb:
      port: 28017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true